const data = {
    products: [
      {
        _id: '1',
        name: 'APPLE',
        category: 'Fruits',
        image: '/images/apple.jpg',
        price: 80,
        unit: 'kg',
        countInStock: 10,
        brand: '',
        rating: 4.0,
        numReviews: 17,
        description: 'Fresh & high quality fruits',
      },
      {
        _id: '2',
        name: 'MANGO',
        category: 'Fruits',
        image: '/images/mango.jpg',
        price: 50,
        unit: 'kg',
        countInStock: 10,
        brand: '',
        rating: 4.5,
        numReviews: 50,
        description: 'Fresh & high quality fruits',
      },
      {
        _id: '3',
        name: 'POTATO',
        category: 'Vegitables',
        image: '/images/potato.jpg',
        price: 15,
        unit: 'kg',
        countInStock: 10,
        brand: '',
        rating: 4.0,
        numReviews: 17,
        description: 'Eat fresh',
      },
      {
        _id: '4',
        name: 'ONION',
        category: 'Vegitables',
        image: '/images/onion-seeds.jpg',
        price: 50,
        unit: 'kg',
        countInStock: 10,
        brand: '',
        rating: 4.5,
        numReviews: 14,
        description: 'Eat Fresh',
      },
      {
        _id: '5',
        name: 'AASHIRVAD ATTA',
        category: 'Grocery',
        image: '/images/atta.jpg',
        price: 400,
        unit: '5kg',
        countInStock: 10,
        brand: 'Aashirvad',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality & no defeact',
      },
      {
        _id: '6',
        name: 'CARROT',
        category: 'Vegitables',
        image: '/images/Carrot.jpg',
        price: 30,
        unit: 'kg',
        countInStock: 10,
        brand: '',
        rating: 4.5,
        numReviews: 15,
        description: 'Eat fresh',
      },
      {
        _id: '7',
        name: 'PINEAPPLE',
        category: 'Fruits',
        image: '/images/pineapple.jpg',
        price: 50,
        unit: 'kg',
        countInStock: 10,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'Eat fresh and Suupper testy',
      },
      {
        _id: '8',
        name: 'ORANGE',
        category: 'Fruits',
        image: '/images/orang.jpg',
        price: 80,
        unit: 'kg',
        countInStock: 19,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'Eat fresh and Suupper testy',
      },
      {
        _id: '9',
        name: 'BRINJEL',
        category: 'Vegitables',
        image: '/images/begun.jpg',
        price: 30,
        unit: 'kg',
        countInStock: 0,
        brand: '',
        rating: 4.5,
        numReviews: 18,
        description: 'Eat fresh',
      },
      {
        _id: '10',
        name: 'MASTER OIL',
        category: 'Grocery',
        image: '/images/masteroil.jpg',
        price: 120,
        unit: '1L',
        countInStock: 20,
        brand: 'Fortune',
        rating: 4.5,
        numReviews: 50,
        description: 'high quality & total fresh',
      },
      {
        _id: '11',
        name: 'MAAZA',
        category: 'Drinks',
        image: '/images/mazza.jpg',
        price: 80,
        unit: '2L',
        countInStock: 60,
        brand: 'Maaza',
        rating: 4.5,
        numReviews: 10,
        description: 'Supper testy Cold Drinks',
      },
      {
        _id: '12',
        name: 'Sprit CAN',
        category: 'Drinks',
        image: '/images/spirte.jpg',
        price: 40,
        unit: 'piece',
        countInStock: 50,
        brand: 'Sprit',
        rating: 4.5,
        numReviews: 10,
        description: 'Supper testy Cold Drinks',
      },
    ],
  };
  export default data;